### ISSUE TITLE
KBS4-5 - Allyation of boc-protected 1,6-diaminohexane 

### ISSUE THREAD

**Issue by KlementineJBS** [KlementineJBS/ELN_USYD_Honours#14]
Link to [HIRAC](https://au-mynotebook.labarchives.com/share/Burrell-Sander_Klementine_kbur3804_Hons/NTIuMHwxMDc1MjAvNDAtNDQvVHJlZU5vZGUvMTk4MjcwMjI0NnwxMzIuMA==) and [original method](https://pubs.acs.org/doi/full/10.1021/ol5018257)

**Outcome**

**Reaction Scheme**

![Optimised allylation of diaminohexane](https://user-images.githubusercontent.com/78768991/119582500-f8041e00-be07-11eb-9138-61da16f7d074.png)

## Method 

**KBS3** (147 mg, 0.460 mmol) was dissolved in dry THF (6 mL) and KOH (226 mg, 4.03 mmol, 8.8 equiv.) was added. The mixture was stirred at room temperature for 1.5 hours and allyl bromide (0.3 mL, 3.55 mmol, 7.7 equiv.) was added. The mixture was left to stir at room temperature for 28 hours and more allyl bromide (0.3 mL) was added. After another 24 hours, more allyl bromide (0.3 mL) was added and the reaction was left to stir at room temperature for 2 days. The mixture was quenched with ammonium chloride (6 mL) and extracted with ethyl acetate (3 x 15 mL) before being purified using automated column chromatography (alumina, EtOAc:hexane = 10:90). As the compound could not be detected in any of the fractions, the column was flushed with methanol (10%) and DCM (90%) and the resulting mixture was concentrated under reduced pressure and re-purified using column chromatography (silica, MeOH:DCM = 10:90). 

**TLC Conditions**

chloroform:MeOH:NH4OH = 80:18:2, permanganate

### NMR

[KBS4_5 impure product.pdf](https://github.com/KlementineJBS/ELN_USYD_Honours/files/6613209/KBS4_5.impure.product.pdf)

### Mass Spec

[KBS4-5.pdf](https://github.com/KlementineJBS/ELN_USYD_Honours/files/6589051/KBS4-5.pdf)
[KBS4-5.zip](https://github.com/KlementineJBS/ELN_USYD_Honours/files/6589054/KBS4-5.zip)

**Comment by KlementineJBS** [comment]
## To consider 

- heat it up?
- need to purify still

**Comment by KlementineJBS** [comment]
## Procedure 

Previously: 2.83 mmol KOH (159 mg, = 9 equiv.) + 0.313 mmol KBS3 (100 mg)

**26.05.21**

- dissolved 147 mg KBS3 in 6 mL dry THF 
- added 226 mg KOH (powder) at 10.15am 
- added allyl bromide (0.3 mL) at 11.45 (after 1.5 hrs "activation" checked via TLC)

**Comment by KlementineJBS** [comment]
**27.05.21**

- TLC'd at 9.45 am (MeOH:chloroform:ammonium hydroxide = 9:90:1) 

<img width="300" src="https://user-images.githubusercontent.com/78768991/119788553-93cf8000-bf15-11eb-87d1-cabcc30dcad7.jpg">

*top spot = allyl bromide**

- TLC'd again at 5.30pm in EtOAc:hexane = 30:70

<img width="300" src="https://user-images.githubusercontent.com/78768991/119788840-d85b1b80-bf15-11eb-8ca5-d35a070a5439.jpg">

- as all allyl bromide seemed to have been consumed, 0.3 mL extra was added

**Comment by KlementineJBS** [comment]
**28.05.21**

- added more allyl bromide (0.3 mL) at 2.40 pm
- left over the weekend (as previous attempt ran for 3 days)

**Comment by KlementineJBS** [comment]
*31.05.21**

- TLC indicated completion (30:70, permanganate)

- added 6 mL ammonium chloride, stirred 10 mins

**Comment by KlementineJBS** [comment]
**31.05.21**

<img width="300" src="https://user-images.githubusercontent.com/78768991/120130203-ec01cd00-c208-11eb-9c38-68861a7f53d2.jpg">

- extraction with 3 x 15 mL EtOAc
- columned with alumina

<img width="373" alt="KBS4-5 alumina column" src="https://user-images.githubusercontent.com/78768991/120255013-67798200-c2ce-11eb-9597-13b0917435a7.png">

**Comment by KlementineJBS** [comment]
**02.06.21**

- flushed column with 10% MeOH in DCM 
- ran new silica column in 10:90 MeOH:DCM 

<img width="373" alt="KBS4-5 column #2" src="https://user-images.githubusercontent.com/78768991/120967675-1d4f3f80-c7ab-11eb-9fb7-7a4097a38af2.png">

- rotvapped down fractions

**Comment by MFernflower** [comment]
@KlementineJBS Maybe use a microwave reactor?

**Comment by KlementineJBS** [comment]
> @KlementineJBS Maybe use a microwave reactor?

Tragically we don't have one available at the moment, or else I'd be keen to try this!

**Comment by MFernflower** [comment]
@KlementineJBS Maybe (If it's safe to do so) use sonication? - even perhaps an ultrasonic cleaner would work?
